FROM python:3.9-bullseye
WORKDIR /app
COPY . .
RUN apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir -r requirements.txt
RUN chmod +x entrypoint.sh
CMD ["./entrypoint.sh"]