channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=23.1.2
- pip:
  - mlflow==2.21.2
  - accelerate==1.6.0
  - astunparse==1.6.3
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - dill==0.3.6
  - gmpy2==2.1.2
  - google-cloud-bigquery==3.31.0
  - numpy==1.25.2
  - pandas==2.1.1
  - pathlib==1.0.1
  - torch==2.3.1
  - transformers==4.42.3
name: mlflow-env
