channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=23.1.2
- pip:
  - mlflow==2.21.2
  - astunparse==1.6.3
  - cloudpickle==2.2.1
  - dill==0.3.6
  - numpy==1.25.2
  - pandas==2.1.1
  - pathlib==1.0.1
  - torch==2.3.1
  - tqdm==4.65.0
name: mlflow-env
